### ISSUE TITLE
Software Center in Elementary OS Freya beta 2 doesn't work

### ISSUE THREAD

**Issue by Dmitry-Kiselev** [snwh/paper-icon-theme#12]
With Paper icon theme Software Center doesn't work. After typing "software-center" in terminal I get this:

dmitry@dmitry:~$ software-center

** (software-center:2326): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-m0szRRqEd5: Connection refused
2015-03-15 18:32:40,292 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
Traceback (most recent call last):
  File "/usr/bin/software-center", line 130, in <module>
    app = SoftwareCenterAppGtk3(options, args)
  File "/usr/share/software-center/softwarecenter/ui/gtk3/app.py", line 407, in __init__
    self.icons)
  File "/usr/share/software-center/softwarecenter/ui/gtk3/panes/historypane.py", line 79, in __init__
    self._get_emblems(self.icons)
  File "/usr/share/software-center/softwarecenter/ui/gtk3/panes/historypane.py", line 199, in _get_emblems
    pb = icons.load_icon(emblem, self.ICON_SIZE, 0)
gi._glib.GError: Icon 'package-install' not present in theme

**Comment by dagolinuxoid** [comment]
У меня на Luna перестал запускаться сегодня (запускается и закрывается сразу, не догрузившись). Удалил к чертям.
 PS.File "/usr/share/apt-xapian-index/plugins/software-center.py", line 120, in index
    url = distro.get_downloadable_icon_url(base_uri, icon)
AttributeError: 'Debian' object has no attribute 'get_downloadable_icon_url'

**Comment by knguye25** [comment]
I got it to work but applied a tweak. So basically when u download the file look for index.theme in the paper folder; mod it by adding "elementary" just before "gnome" on the line where it says "inherit = blah, blah, gnome, blah"

**Comment by varlesh** [comment]
Software Center not needed, use APT or Synaptic.

**Comment by dagolinuxoid** [comment]
Synaptic is nice, software center purged )

**Comment by Dmitry-Kiselev** [comment]
I have nothing against Synaptic or APT and it's actually main way to install new apps for me, but Software Center is pre-installed app in some operating systems, so I think it should work.
